### ISSUE TITLE
Apply topic(s) to improve findability?

### ISSUE THREAD

**Issue by katrinleinweber** [gjtorikian/repository-sync#42]
Hello and thanks for publishing this tool :-)

Several similar projects as yours have set the [topic `git-sync`](https://github.com/topics/git-sync). Have you considered also [applying that topic](https://help.github.com/articles/classifying-your-repository-with-topics/)? There is also the [`repository-synchronization`](https://github.com/topics/repository-synchronization), albeit rarer.

Either way, your repo would appear in the topic overview page(s) then, which helps people find it and helps curators and advisors to impartially point people to a topic page, rather than to specific projects.

Thanks you, and kind regards!

**Comment by gjtorikian** [comment]
Sure, I've done it. Thanks!

**Comment by katrinleinweber** [comment]
Cool! You're welcome :-)
